-- Accelerate database schemata --

-- Accelerate schema initialization starts here --

CREATE TABLE ACC_TEAM_MAST (
    ATM_TEAM_CODE SERIAL PRIMARY KEY,
    ATM_TEAM_NAME VARCHAR (30),
    ATM_TEAM_SHORT_NAME VARCHAR (8),
    ATM_STATUS VARCHAR (1) NOT NULL,
    ATM_TEAM_CRT_BY INT,
    ATM_TEAM_CRT_DATE TIMESTAMP,
    ATM_TEAM_UPD_BY INT,
    ATM_TEAM_UPD_DATE TIMESTAMP,
    ATM_TEAM_REMARKS VARCHAR (50)
);

CREATE TABLE ACC_ROLE_MAST (
    ARM_ROLE_NAME VARCHAR (15),
    ARM_ROLE_CODE VARCHAR (2) PRIMARY KEY
);

CREATE TABLE ACC_EMPLOYEE_MAST (
    AEM_EMP_CODE SERIAL PRIMARY KEY,
    AEM_EMP_FIRST_NAME VARCHAR (30) NOT NULL,
    AEM_EMP_MIDDLE_NAME VARCHAR (30),
    AEM_EMP_LAST_NAME VARCHAR (30),
    AEM_EMP_PHONE_NO VARCHAR (15),
    AEM_EMP_EMG_PHONE_NO VARCHAR (15),
    AEM_EMP_DOB DATE,
    AEM_EMP_ADDR1 VARCHAR (100),
    AEM_EMP_ADDR2 VARCHAR (100),
    AEM_EMP_LANDMARK VARCHAR (50),
    AEM_EMP_CITY VARCHAR (30),
    AEM_EMP_STATE VARCHAR (30),
    AEM_EMP_COUNTRY VARCHAR (20),
    AEM_EMP_POST_CODE VARCHAR (10),
    AEM_EMP_CRT_TIME TIMESTAMP,
    AEM_EMP_CRT_BY INT,
    AEM_EMP_UPD_TIME TIMESTAMP,
    AEM_EMP_UPD_BY INT,
    AEM_EMP_TEAM INT REFERENCES ACC_TEAM_MAST (ATM_TEAM_CODE),
    AEM_EMP_ROLE VARCHAR (2) REFERENCES ACC_ROLE_MAST (ARM_ROLE_CODE),
    AEM_EMP_STATUS VARCHAR (1),
    AEM_EMP_SHORT_NAME VARCHAR (8),
    AEM_EMP_JOINING_DATE DATE NOT NULL,
    AEM_EMP_REMARKS VARCHAR (30)
);

CREATE TABLE ACC_EMP_LOGIN (
    AEL_SEQ_ID SERIAL,
    AEL_EMP_CODE INT REFERENCES ACC_EMPLOYEE_MAST (AEM_EMP_CODE),
    AEL_LOGIN_ID VARCHAR (15) PRIMARY KEY ,
    AEL_LOGIN_PASSWORD VARCHAR (32),
    AEL_UPD_DATE TIMESTAMP
);

CREATE TABLE ACC_PROJECT_MAST (
    APM_PROJ_CODE SERIAL PRIMARY KEY ,
    APM_PROJ_NAME VARCHAR(50),
    APM_RPOJ_TEAM INT REFERENCES ACC_TEAM_MAST (ATM_TEAM_CODE),
    APM_PROJ_SUMMARY VARCHAR (150),
    APM_PROJ_DESCRIPTION TEXT,
    APM_PROJ_START_DATE DATE,
    APM_PROJ_EFFORT_DAYS INT,
    APM_PROJ_MILESTONES INT,
    APM_PROJ_COMPLETED INT,
    APM_PROJ_PENDING INT,
    APM_PROJ_STATUS INT NOT NULL,
    APM_PROJ_REMARKS VARCHAR (150),
    APM_PROJ_CRT_BY INT,
    APM_PROJ_CRT_DATE TIMESTAMP,
    APM_PROJ_UPD_BY INT,
    APM_PROJ_UPD_DATE TIMESTAMP
);

CREATE TABLE ACC_MILESTONE_LIST (
    AML_MILE_CODE SERIAL,
    AML_PROJ_CODE INT REFERENCES ACC_PROJECT_MAST (APM_PROJ_CODE),
    AML_TEAM_CODE INT REFERENCES ACC_TEAM_MAST (ATM_TEAM_CODE),
    AML_MILE_EFFORT_DAYS INT,
    AML_MILE_SL_NUM INT,
    AML_MILE_NAME VARCHAR (30),
    AML_MILE_DESCRIPTION TEXT,
    AML_MILE_TASKS INT,
    AML_MILE_COMPLETED INT,
    AML_MILE_PENDING INT,
    AML_MILE_STATUS VARCHAR (1) NOT NULL,
    AML_REMARKS TEXT,
    PRIMARY KEY (AML_PROJ_CODE,AML_MILE_SL_NUM)
);

CREATE TABLE ACC_PROJTASK_LIST (
    APL_TASK_CODE SERIAL,
    APL_MILE_CODE INT,
    APL_TEAM_CODE INT REFERENCES ACC_TEAM_MAST (ATM_TEAM_CODE),
    APL_TASK_SL_NUM INT,
    APL_TASK_NAME VARCHAR (30),
    APL_TASK_DESCRIPTION TEXT,
    APL_TASK_ASSIGNED INT,
    APL_TASK_STATUS VARCHAR (1),
    APL_TASK_DEPENDENCY INT,
    APL_TASK_DEPENDENT INT,
    APL_MAN_HOURS INT,
    APL_TIME_TAKEN INT,
    APL_START_TIME TIMESTAMP,
    APL_END_TIME TIMESTAMP,
    APL_REMARKS TEXT,
    PRIMARY KEY (APL_MILE_CODE,APL_TEAM_CODE,APL_TASK_SL_NUM)
);

CREATE TABLE ACC_ISSUE_LIST (
    AIL_ISSUE_CODE SERIAL PRIMARY KEY ,
    AIL_ISSUE_SUMMARY VARCHAR (150),
    AIL_ISSUE_DESCRIPTION TEXT,
    AIL_ISSUE_TYPE VARCHAR (1) NOT NULL,
    AIL_ISSUE_TEAM INT REFERENCES ACC_TEAM_MAST (ATM_TEAM_CODE),
    AIL_ASSIGNED_TO INT,
    AIL_STATUS VARCHAR (1) NOT NULL,
    AIL_TIME_TAKEN INT,
    AIL_START_TIME TIMESTAMP,
    AIL_END_TIME TIMESTAMP,
    AIL_CRT_BY INT,
    AIL_CRT_TIME TIMESTAMP,
    AIL_UPD_BY INT,
    AIL_UPD_TIME TIMESTAMP,
    AIL_REMARKS TEXT
);

CREATE TABLE ACC_TASK_MAST (
    ATM_TASK_CODE SERIAL PRIMARY KEY ,
    ATM_TEAM_CODE INT REFERENCES ACC_TEAM_MAST (ATM_TEAM_CODE),
    ATM_TASK_NAME VARCHAR (30),
    ATM_TASK_DESCRIPTION TEXT,
    ATM_TASK_ASSIGNED INT,
    ATM_TASK_STATUS VARCHAR (1) NOT NULL ,
    ATM_TASK_DEPENDENCY INT,
    ATM_TASK_DEPENDENT INT,
    ATM_MAN_HOURS INT,
    ATM_TIME_TAKEN INT,
    ATM_START_TIME TIMESTAMP,
    ATM_END_TIME TIMESTAMP,
    ATM_REMARKS TEXT
);

CREATE TABLE ACC_PER_TASK (
    APT_TASK_CODE SERIAL PRIMARY KEY ,
    APT_TEAM_CODE INT REFERENCES ACC_TEAM_MAST (ATM_TEAM_CODE),
    APT_TASK_NAME VARCHAR (30),
    APT_TASK_DESCRIPTION TEXT,
    APT_ASSIGNED INT,
    APT_TASK_STATUS VARCHAR (1) NOT NULL,
    APT_TASK_DEPENDENCY INT,
    APT_TIME_TAKEN INT,
    APT_START_TIME TIMESTAMP,
    APT_END_TIME TIMESTAMP,
    APT_REMARKS TEXT
);

CREATE TABLE ACC_MANAGE_MAST (
    AMM_EMP_REP_MANAGER INT REFERENCES ACC_TEAM_MAST (ATM_TEAM_CODE),
    AMM_EMP_MANAGER INT REFERENCES ACC_TEAM_MAST (ATM_TEAM_CODE),
    CHECK ( AMM_EMP_REP_MANAGER != AMM_EMP_MANAGER ),
    PRIMARY KEY (AMM_EMP_MANAGER,AMM_EMP_REP_MANAGER)
);

-- Accelerate schema initialization ends here --

-- Accelerate spring boot session schema initialization starts here --

CREATE TABLE SPRING_SESSION (
PRIMARY_ID VARCHAR(36) NOT NULL,
SESSION_ID VARCHAR(36) NOT NULL,
CREATION_TIME BIGINT NOT NULL,
LAST_ACCESS_TIME BIGINT NOT NULL,
MAX_INACTIVE_INTERVAL INT NOT NULL,
EXPIRY_TIME BIGINT NOT NULL,
PRINCIPAL_NAME VARCHAR(100),
CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
SESSION_PRIMARY_ID CHAR(36) NOT NULL,
ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
ATTRIBUTE_BYTES BYTEA NOT NULL,
CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

-- Accelerate spring boot session schema initialization ends here --

-- Default data entries for schema starts here --

INSERT INTO ACC_TEAM_MAST (ATM_TEAM_NAME,ATM_TEAM_SHORT_NAME,ATM_STATUS,ATM_TEAM_CRT_DATE,ATM_TEAM_REMARKS) VALUES ('IT Administration','ADMIN','A',NOW(),'Organisation Infrastructure Administration');

INSERT INTO ACC_ROLE_MAST (ARM_ROLE_NAME,ARM_ROLE_CODE) VALUES ('SuperUser','SU');
INSERT INTO ACC_ROLE_MAST (ARM_ROLE_NAME,ARM_ROLE_CODE) VALUES ('Manager','TL');
INSERT INTO ACC_ROLE_MAST (ARM_ROLE_NAME,ARM_ROLE_CODE) VALUES ('Resource','RS');
INSERT INTO ACC_ROLE_MAST (ARM_ROLE_NAME,ARM_ROLE_CODE) VALUES ('Level 1','L1');
INSERT INTO ACC_ROLE_MAST (ARM_ROLE_NAME,ARM_ROLE_CODE) VALUES ('Level 2','L2');

INSERT INTO ACC_EMPLOYEE_MAST (AEM_EMP_FIRST_NAME,AEM_EMP_CRT_TIME,AEM_EMP_TEAM,AEM_EMP_ROLE,AEM_EMP_JOINING_DATE) VALUES ('SuperUser',NOW(),(SELECT ATM_TEAM_CODE FROM ACC_TEAM_MAST WHERE ATM_TEAM_SHORT_NAME='ADMIN'),'SU',NOW());

INSERT INTO ACC_EMP_LOGIN (AEL_EMP_CODE,AEL_LOGIN_ID,AEL_LOGIN_PASSWORD,AEL_UPD_DATE) VALUES ((SELECT AEM_EMP_CODE FROM ACC_EMPLOYEE_MAST WHERE AEM_EMP_FIRST_NAME='SuperUser'),'superuser','ADBBC196EB5F1B9B205EB4BB1F8FEF41',NOW())

-- Default data entries for schema ends here --

